Backport: Require minitest/mock to fix Minitest::Mock uninitialized constant error
Fix test failures caused by Minitest::Mock not being automatically loaded
in newer versions of minitest. This error manifests as:

  NameError: uninitialized constant Minitest::Mock

in test files that use Minitest::Mock (e.g., metadata_test.rb).

Solution: Explicitly require 'minitest/mock' in test/helper.rb after
requiring 'minitest/autorun'.

Related Tickets:
- Original fix in InSpec-5: commit 1f0a1d29f by Sathish <sbabu@progress.com>
- Date: December 19, 2025

Testing:
- Fixes NameError in test/unit/profiles/metadata_test.rb
- Allows Minitest::Mock to be used throughout test suite
- No side effects on existing tests

Cherry-picked from InSpec-5 commit: 1f0a1d29ffeaf4c48ae0782451b827c528e78fc8

Signed-off-by: Samir Anand <sanand@progress.com>